# Generated by Django 5.1 on 2024-08-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Iten',
            new_name='Item',
        ),
    ]
